---
- name: Add all repo needed in hosts
  hosts: all
  remote_user: opc
  become: yes
  become_method: su

  tasks:
    - name: Adding logstash repo
      ansible.builtin.yum_repository:
        name: elastic_stack_repo_8
        description: Repository for logstash 8.x
        file: repo_logstash_8x
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
